# Generated by Django 3.1.4 on 2021-03-04 09:13

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('roll_number', models.CharField(max_length=128)),
                ('date_of_registration', models.DateField()),
                ('department', models.CharField(help_text="For example, 'Electrical Engineering'", max_length=128)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('permanent_address', models.TextField(default='')),
                ('scholarship', models.CharField(choices=[('I', 'Institute'), ('CSIR', 'CSIR'), ('UGC', 'UGC')], max_length=128, null=True, verbose_name='Scholarship: Institute / CSIR / UGC')),
                ('date_of_scholarship', models.DateField(default='', null=True, verbose_name='Date from which scholarship is awarded')),
                ('course_work_completed_on', models.DateField(default='', help_text='Give the expected date', null=True)),
                ('course_work_completed_by', models.CharField(max_length=128)),
                ('marriage_certificate', models.FileField(null=True, upload_to='marriage_certificates/')),
                ('joint_photograph_with_spouse', models.FileField(null=True, upload_to='photo_with_spouse/')),
                ('coursework_grade_sheet', models.FileField(null=True, upload_to='grade_sheet/')),
                ('recommendation_of_guide_for_accomodation', models.FileField(null=True, upload_to='guide_recommendation/')),
                ('spouse_name', models.CharField(default='Name of your Spouse', max_length=128, null=True)),
                ('spouse_roll_number', models.CharField(default='N/A', max_length=128, null=True)),
                ('spouse_designation', models.CharField(default='N/A', max_length=128, null=True)),
                ('marriage_certificate_verified', models.BooleanField(default=False)),
                ('joint_photograph_with_spouse_verified', models.BooleanField(default=False)),
                ('coursework_grade_sheet_verified', models.BooleanField(default=False)),
                ('recommendation_of_guide_for_accomodation_verified', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, default='Your Documents are not yet verified!', null=True)),
                ('acadsection_feedback', models.TextField(blank=True, default='', null=True, verbose_name='Feedback')),
                ('waitlist_Type1', models.IntegerField(db_index=True, default=-1, editable=False)),
                ('waitlist_Tulsi', models.IntegerField(db_index=True, default=-1, editable=False)),
                ('waitlist_MRSB', models.IntegerField(db_index=True, default=-1, editable=False)),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Applied')),
                ('verified_time', models.DateTimeField(blank=True, null=True, verbose_name='Date of verification by HCU')),
                ('occupied_Type1', models.BooleanField(default=False)),
                ('occupied_Tulsi', models.BooleanField(default=False)),
                ('occupied_MRSB', models.BooleanField(default=False)),
                ('scholarship_awarded_upto', models.DateField(blank=True, null=True, verbose_name='Initially the scholarship awarded up to')),
                ('acad_details_verified', models.BooleanField(default=False, verbose_name='The academic details are verified and found correct')),
                ('acad_details_verification_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Verification Date by Academic Section')),
                ('application_received_by_hcu_date', models.DateTimeField(blank=True, null=True, verbose_name='Application Received by H.C.Unit Date:')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=125, unique=True)),
                ('applicant', models.ManyToManyField(blank=True, to='portal.Applicant')),
            ],
            options={
                'verbose_name': 'Buffered',
                'verbose_name_plural': 'Buffered',
            },
        ),
        migrations.CreateModel(
            name='VacatedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=125, unique=True)),
                ('applicant', models.ManyToManyField(blank=True, to='portal.Applicant')),
            ],
            options={
                'verbose_name': 'Vacated',
                'verbose_name_plural': 'Vacated',
            },
        ),
        migrations.CreateModel(
            name='OccupiedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=125, unique=True)),
                ('applicant', models.ManyToManyField(blank=True, to='portal.Applicant')),
            ],
            options={
                'verbose_name': 'Occupied',
                'verbose_name_plural': 'Occupied',
            },
        ),
    ]
