# Generated by Django 3.0.7 on 2021-02-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0093_auto_20210215_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='course_work_completed_on',
            field=models.DateField(help_text='Give the expected date', null=True),
        ),
    ]
